# Generated by Django 3.0.5 on 2020-04-29 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200427_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('1[345678]\\d{9}')]),
        ),
    ]
